### ISSUE TITLE
Set up travis CI

### ISSUE THREAD

**Issue by BrunoSanchez** [vcristiani/galaxy-chop#32]
Copy from grispy or similar the .travis.yml

Search how to make travis track our repo in www

**Comment by nvillagra** [comment]
The preliminarie code looks like this

```
language: python
sudo: true

before_install:
  ...

install:
  - pip install tox

script:
  - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=style 
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=coverage
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=docstyle
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=docs
          dist: xenial
          sudo: true
          
        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true

        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true

        - python: 3.6
          env: TOXENV=py36
          dist: xenial
          sudo: true
```
What do you think?  @BrunoSanchez @antotaverna
